
const _arg_desc = KW(

# series args
:label 				=> "String type. The label for a series, which appears in a legend.  If empty, no legend entry is added.",
:seriescolor 		=> "Color type. The base color for this series.  `:auto` (the default) will select a color from the subplot's `color_palette`, based on the order it was added to the subplot",
:seriesalpha 		=> "Number in [0,1]. The alpha/opacity override for the series.  `nothing` (the default) means it will take the alpha value of the color.",
:seriestype 		=> "Symbol. This is the identifier of the type of visualization for this series. Choose from $(_allTypes) or any series recipes which are defined.",
:linestyle 			=> "",
:linewidth         	=> "",
:linecolor         	=> "",
:linealpha         	=> "",
:fillrange         	=> "",
:fillcolor         	=> "",
:fillalpha         	=> "",
:markershape       	=> "",
:markercolor       	=> "",
:markeralpha       	=> "",
:markersize        	=> "",
:markerstrokestyle 	=> "",
:markerstrokewidth 	=> "",
:markerstrokecolor 	=> "",
:markerstrokealpha 	=> "",
:bins              	=> "",
:smooth            	=> "",
:group             	=> "",
:x                 	=> "",
:y                 	=> "",
:z                 	=> "",
:marker_z          	=> "",
:levels            	=> "",
:orientation       	=> "",
:bar_position      	=> "",
:bar_width         	=> "",
:bar_edges         	=> "",
:xerror            	=> "",
:yerror            	=> "",
:ribbon            	=> "",
:quiver            	=> "",
:arrow             	=> "",
:normalize         	=> "",
:weights           	=> "",
:contours          	=> "",
:match_dimensions  	=> "",
:subplot           	=> "",
:series_annotations => "",
:primary            => "",

# plot args
:plot_title               => "",
:background_color         => "",
:background_color_outside => "",
:foreground_color         => "",
:size                     => "",
:pos                      => "",
:window_title             => "",
:show                     => "",
:layout                   => "",
:link                     => "",
:overwrite_figure         => "",
:html_output_format       => "",

# subplot args
:title                    => "",
:title_location           => "",
:titlefont                => "",
:background_color_subplot => "",
:background_color_legend  => "",
:background_color_inside  => "",
:foreground_color_subplot => "",
:foreground_color_legend  => "",
:foreground_color_grid    => "",
:foreground_color_title   => "",
:color_palette            => "",
:legend                   => "",
:colorbar                 => "",
:legendfont               => "",
:grid                     => "",
:annotations              => "",
:projection               => "",
:aspect_ratio             => "",
:margin                   => "",
:left_margin              => "",
:top_margin               => "",
:right_margin             => "",
:bottom_margin            => "",
:subplot_index            => "",

# axis args
:guide     				  => "",
:lims      				  => "",
:ticks     				  => "",
:scale     				  => "",
:rotation  				  => "",
:flip      				  => "",
:tickfont  				  => "",
:guidefont 				  => "",
:foreground_color_axis    => "",
:foreground_color_border  => "",
:foreground_color_text    => "",
:foreground_color_guide   => "",

)