
const _arg_desc = KW(

# series args
:label 				=> "String type. The label for a series, which appears in a legend.  If empty, no legend entry is added.",
:seriescolor 		=> "Color Type. The base color for this series.  `:auto` (the default) will select a color from the subplot's `color_palette`, based on the order it was added to the subplot",
:seriesalpha 		=> "Number in [0,1]. The alpha/opacity override for the series.  `nothing` (the default) means it will take the alpha value of the color.",
:seriestype 		=> "Symbol. This is the identifier of the type of visualization for this series. Choose from $(_allTypes) or any series recipes which are defined.",
:linestyle 			=> "Symbol. Style of the line (for path and bar stroke).  Choose from $(_allStyles)",
:linewidth         	=> "Number. Width of the line (in pixels)",
:linecolor         	=> "Color Type. Color of the line (for path and bar stroke).  `:match` will take the value from `:seriescolor`, (though histogram/bar types use `:black` as a default).",
:linealpha         	=> "Number in [0,1]. The alpha/opacity override for the line.  `nothing` (the default) means it will take the alpha value of linecolor.",
:fillrange         	=> "Number or AbstractVector.  Fills area from this to y for line-types, sets the base for bar/stick types, and similar for other types.",
:fillcolor         	=> "Color Type. Color of the filled area of path or bar types.  `:match` will take the value from `:seriescolor`.",
:fillalpha         	=> "Number in [0,1]. The alpha/opacity override for the fill area.  `nothing` (the default) means it will take the alpha value of fillcolor.",
:markershape       	=> "Symbol, Shape, or AbstractVector. Choose from $(_allMarkers).",
:markercolor       	=> "Color Type. Color of the interior of the marker or shape. `:match` will take the value from `:seriescolor`.",
:markeralpha       	=> "Number in [0,1]. The alpha/opacity override for the marker interior.  `nothing` (the default) means it will take the alpha value of markercolor.",
:markersize        	=> "Number or AbstractVector. Size (radius pixels) of the markers.",
:markerstrokestyle 	=> "Symbol. Style of the marker stroke (border).  Choose from $(_allStyles)",
:markerstrokewidth 	=> "Number. Width of the marker stroke (border. in pixels)",
:markerstrokecolor 	=> "Color Type. Color of the marker stroke (border).  `:match` will take the value from `:seriescolor`.",
:markerstrokealpha 	=> "Number in [0,1]. The alpha/opacity override for the marker stroke (border).  `nothing` (the default) means it will take the alpha value of markerstrokecolor.",
:bins              	=> "Integer, NTuple{2,Integer}, AbstractVector. For histogram-types, defines the number of bins, or the edges, of the histogram.",
:smooth            	=> "Bool.  Add a regression line?",
:group             	=> "AbstractVector. Data is split into a separate series, one for each unique value in `group`.",
:x                 	=> "Various. Input data. First Dimension",
:y                 	=> "Various. Input data. Second Dimension",
:z                 	=> "Various. Input data. Third Dimension. May be wrapped by a `Surface` for surface and heatmap types.",
:marker_z          	=> "AbstractVector. z-values for each series data point, which correspond to the color to be used from a markercolor gradient.",
:levels            	=> "Integer, NTuple{2,Integer}. Number of levels (or x-levels/y-levels) for a contour type.",
:orientation       	=> "Symbol.  Horizontal or vertical orientation for bar types.  Values `:h`, `:hor`, `:horizontal` correspond to horizontal (sideways, anchored to y-axis), and `:v`, `:vert`, and `:vertical` correspond to vertical (the default).",
:bar_position      	=> "Symbol.  Choose from `:overlay` (default), `:stack`.  (warning: May not be implemented fully)",
:bar_width         	=> "nothing or Number. Width of bars in data coordinates. When nothing, chooses based on x (or y when `orientation = :h`).",
:bar_edges         	=> "Bool.  Align bars to edges (true), or centers (the default)?",
:xerror            	=> "AbstractVector or 2-Tuple of Vectors. x (horizontal) error relative to x-value.  If 2-tuple of vectors, the first vector corresponds to the left error (and the second to the right)",
:yerror            	=> "AbstractVector or 2-Tuple of Vectors. y (vertical) error relative to y-value.  If 2-tuple of vectors, the first vector corresponds to the bottom error (and the second to the top)",
:ribbon            	=> "Number or AbstractVector.  Creates a fillrange around the data points.",
:quiver            	=> "AbstractVector or 2-Tuple of vectors.  The directional vectors U,V which specify velocity/gradient vectors for a quiver plot.",
:arrow             	=> "nothing (no arrows), Bool (if true, default arrows), Arrow object, or arg(s) that could be style or head length/widths.  Defines arrowheads that should be displayed at the end of path line segments (just before a NaN and the last non-NaN point).  Used in quiverplot, streamplot, or similar.",
:normalize         	=> "Bool. Should normalize histogram types?  Trying for area == 1.",
:weights           	=> "AbstractVector. Used in histogram types for weighted counts.",
:contours          	=> "Bool. Add contours to the side-grids of 3D plots?  Used in surface/wireframe.",
:match_dimensions  	=> "Bool. For heatmap types... should the first dimension of a matrix (rows) correspond to the first dimension of the plot (x-axis)?  The default is false, which matches the behavior of Matplotlib, Plotly, and others.  Note: when passing a function for z, the function should still map `(x,y) -> z`.",
:subplot           	=> "",
:series_annotations => "",
:primary            => "",

# plot args
:plot_title               => "",
:background_color         => "",
:background_color_outside => "",
:foreground_color         => "",
:size                     => "",
:pos                      => "",
:window_title             => "",
:show                     => "",
:layout                   => "",
:link                     => "",
:overwrite_figure         => "",
:html_output_format       => "",

# subplot args
:title                    => "",
:title_location           => "",
:titlefont                => "",
:background_color_subplot => "",
:background_color_legend  => "",
:background_color_inside  => "",
:foreground_color_subplot => "",
:foreground_color_legend  => "",
:foreground_color_grid    => "",
:foreground_color_title   => "",
:color_palette            => "",
:legend                   => "",
:colorbar                 => "",
:legendfont               => "",
:grid                     => "",
:annotations              => "",
:projection               => "",
:aspect_ratio             => "",
:margin                   => "",
:left_margin              => "",
:top_margin               => "",
:right_margin             => "",
:bottom_margin            => "",
:subplot_index            => "",

# axis args
:guide     				  => "",
:lims      				  => "",
:ticks     				  => "",
:scale     				  => "",
:rotation  				  => "",
:flip      				  => "",
:tickfont  				  => "",
:guidefont 				  => "",
:foreground_color_axis    => "",
:foreground_color_border  => "",
:foreground_color_text    => "",
:foreground_color_guide   => "",

)