function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Plots.py_add_series, (Plots.Plot{Plots.PyPlotBackend}, Plots.Series,))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Array{Float64, 1},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Base.StepRange{Int64, Int64},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Function,))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Array{Plots.OHLC, 1},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Array{Float64, 1},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Base.LinSpace{Float64},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, DataFrames.DataFrame,))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Array{Int64, 1},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Array{Union{UTF8String, ASCIIString}, 1},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Array{Function, 1},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Array{ASCIIString, 1},))
    precompile(Plots._plot!, (Plots.Plot{Plots.UnicodePlotsBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Base.FloatRange{Float64},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots._plot!, (Plots.Plot{Plots.UnicodePlotsBackend}, Base.Dict{Symbol, Any}, Array{Float64, 1},))
    precompile(Plots._plot!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Array{Float64, 2},))
    precompile(Plots._add_defaults!, (Base.Dict{Symbol, Any}, Plots.Plot{Plots.UnicodePlotsBackend}, Plots.Subplot{Plots.UnicodePlotsBackend}, Int64,))
    precompile(Plots._before_layout_calcs, (Plots.Plot{Plots.PyPlotBackend},))
    precompile(Plots._apply_series_recipe, (Plots.Plot{Plots.UnicodePlotsBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots._add_defaults!, (Base.Dict{Symbol, Any}, Plots.Plot{Plots.PyPlotBackend}, Plots.Subplot{Plots.PyPlotBackend}, Int64,))
    precompile(Plots._apply_series_recipe, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots.setup_ijulia, ())
    precompile(Plots.call, (Type{Plots.Plot{Plots.UnicodePlotsBackend}}, Plots.UnicodePlotsBackend, Int64, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Array{Plots.Series, 1}, Void, Array{Plots.Subplot, 1}, Base.Dict{Any, Plots.Subplot}, Plots.EmptyLayout, Array{Plots.Subplot, 1}, Bool,))
    precompile(Plots.expand_extrema!, (Plots.Subplot{Plots.UnicodePlotsBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots.create_grid_vcat, (Expr,))
    precompile(Plots.expand_extrema!, (Plots.Subplot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots.update_child_bboxes!, (Plots.GridLayout, Array{Measures.Length{:mm, Float64}, 1},))
    precompile(Plots.preprocessArgs!, (Base.Dict{Symbol, Any},))
    precompile(Plots.call, (Type{Plots.Plot{Plots.PyPlotBackend}}, Plots.PyPlotBackend, Int64, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Array{Plots.Series, 1}, Void, Array{Plots.Subplot, 1}, Base.Dict{Any, Plots.Subplot}, Plots.EmptyLayout, Array{Plots.Subplot, 1}, Bool,))
    precompile(Plots.fix_xy_lengths!, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots._update_min_padding!, (Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.warnOnUnsupported_args, (Plots.PyPlotBackend, Base.Dict{Symbol, Any},))
    precompile(Plots.build_layout, (Plots.GridLayout, Int64,))
    precompile(Plots.build_layout, (Plots.GridLayout, Int64, Array{Plots.Plot, 1},))
    precompile(Plots.warnOnUnsupported, (Plots.UnicodePlotsBackend, Base.Dict{Symbol, Any},))
    precompile(Plots.link_axes!, (Plots.GridLayout, Symbol,))
    precompile(Plots.warnOnUnsupported, (Plots.PyPlotBackend, Base.Dict{Symbol, Any},))
    precompile(Plots._update_plot_args, (Plots.Plot{Plots.UnicodePlotsBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots.font, (Int64,))
    precompile(Plots.recompute_lengths, (Array{Measures.Measure, 1},))
    precompile(Plots._update_plot_object, (Plots.Plot{Plots.PyPlotBackend},))
    precompile(Plots.font, (Symbol,))
    precompile(Plots.create_grid, (Expr,))
    precompile(Plots.slice_arg!, (Array{Any, 1}, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Symbol, Void, Int64,))
    precompile(Plots.pickDefaultBackend, ())
    precompile(Plots.default_should_widen, (Plots.Axis,))
    precompile(Plots.setup_atom, ())
    precompile(Plots.slice_arg!, (Array{Any, 1}, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Symbol, Symbol, Int64,))
    precompile(Plots.my_hist_2d, (Array{Any, 1}, Array{Float64, 1}, Array{Float64, 1}, Int64,))
    precompile(Plots.slice_arg!, (Array{Any, 1}, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Symbol, ASCIIString, Int64,))
    precompile(Plots.create_grid_curly, (Expr,))
    precompile(Plots.slice_arg!, (Array{Any, 1}, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Symbol, Bool, Int64,))
    precompile(Plots.slice_arg!, (Array{Any, 1}, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Symbol, Int64, Int64,))
    precompile(Plots.my_hist, (Array{Any, 1}, Array{Float64, 1}, Int64,))
    precompile(Plots.getpctrange, (Int64,))
    precompile(Plots.call, (Type{Plots.ColorGradient}, Array{Symbol, 1},))
    precompile(Plots.default, (Symbol,))
    precompile(Plots.process_axis_arg!, (Base.Dict{Symbol, Any}, Symbol, Symbol,))
    precompile(Plots.pie_labels, (Plots.Subplot{Plots.PyPlotBackend}, Plots.Series,))
    precompile(Plots.slice_arg!, (Array{Any, 1}, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Symbol, Measures.Length{:mm, Float64}, Int64,))
    precompile(Plots.py_path, (Array{Float64, 1}, Array{Float64, 1},))
    precompile(Plots._update_min_padding!, (Plots.GridLayout,))
    precompile(Plots.warnOnUnsupported_scales, (Plots.UnicodePlotsBackend, Base.Dict{Symbol, Any},))
    precompile(Plots.slice_arg!, (Array{Any, 1}, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Symbol, Plots.Font, Int64,))
    precompile(Plots.process_axis_arg!, (Base.Dict{Symbol, Any}, Tuple{Int64, Int64}, Symbol,))
    precompile(Plots.slice_arg!, (Array{Any, 1}, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Symbol, Array{Any, 1}, Int64,))
    precompile(Plots.default, (Symbol, Tuple{Int64, Int64},))
    precompile(Plots.warnOnUnsupported_scales, (Plots.PyPlotBackend, Base.Dict{Symbol, Any},))
    precompile(Plots.axis_limits, (Plots.Axis, Bool,))
    precompile(Plots.default, (Symbol, Bool,))
    precompile(Plots.getColorZ, (Plots.ColorGradient, Float64,))
    precompile(Plots._update_plot_args, (Plots.Plot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any},))
    precompile(Plots.call, (Type{Plots.Surface}, Function, Base.FloatRange{Float64}, Base.FloatRange{Float64},))
    precompile(Plots.font, (Symbol,))
    precompile(Plots.process_axis_arg!, (Base.Dict{Symbol, Any}, Base.StepRange{Int64, Int64}, Symbol,))
    precompile(Plots.call, (Array{Any, 1}, Type{Plots.Subplot}, Plots.UnicodePlotsBackend,))
    precompile(Plots.extractGroupArgs, (Array{ASCIIString, 1}, Array{Float64, 1},))
    precompile(Plots._update_subplot_args, (Array{Any, 1}, Plots.Plot{Plots.UnicodePlotsBackend}, Plots.Subplot{Plots.UnicodePlotsBackend}, Base.Dict{Symbol, Any}, Int64,))
    precompile(Plots.call, (Array{Any, 1}, Type{Plots.Subplot}, Plots.PyPlotBackend,))
    precompile(Plots._update_subplot_args, (Array{Any, 1}, Plots.Plot{Plots.PyPlotBackend}, Plots.Subplot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Int64,))
    precompile(Plots.extractGroupArgs, (Array{Union{UTF8String, ASCIIString}, 1},))
    precompile(Plots.bbox_to_pcts, (Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}}, Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}, Bool,))
    precompile(Plots.plot, (Array{Any, 1}, Array{Float64, 1},))
    precompile(Plots.py_marker, (Plots.Shape,))
    precompile(Plots.getindex, (Plots.Subplot{Plots.UnicodePlotsBackend}, Symbol,))
    precompile(Plots.getindex, (Plots.Subplot{Plots.PyPlotBackend}, Symbol,))
    precompile(Plots.discrete_value!, (Plots.Axis, Array{Union{UTF8String, ASCIIString}, 1},))
    precompile(Plots.prepare_output, (Plots.Plot{Plots.PyPlotBackend},))
    precompile(Plots.update_inset_bboxes!, (Plots.Plot{Plots.PyPlotBackend},))
    precompile(Plots.add_layout_pct!, (Base.Dict{Symbol, Any}, Expr, Int64, Int64,))
    precompile(Plots.process_axis_arg!, (Base.Dict{Symbol, Any}, ASCIIString, Symbol,))
    precompile(Plots.call, (Type{Plots.Shape}, Array{Float64, 1}, Array{Float64, 1},))
    precompile(Plots.plot, (Array{Any, 1}, Base.LinSpace{Float64}, Array{Float64, 2},))
    precompile(Plots.call, (Array{Any, 1}, Type{Plots.EmptyLayout}, Plots.RootLayout,))
    precompile(Plots.plot, (Array{Any, 1}, Function, Function,))
    precompile(Plots.should_add_to_legend, (Plots.Series,))
    precompile(Plots.plot, (Array{Any, 1}, DataFrames.DataFrame, Symbol,))
    precompile(Plots.plot, (Array{Any, 1}, Array{Plots.OHLC, 1},))
    precompile(Plots.convertToAnyVector, (Array{Float64, 2}, Base.Dict{Symbol, Any},))
    precompile(Plots.plot, (Array{Any, 1}, Array{Float64, 1}, Array{Float64, 1},))
    precompile(Plots.plot, (Array{Any, 1}, Array{ASCIIString, 1}, Array{Float64, 1},))
    precompile(Plots.plot!, (Array{Any, 1}, Plots.Plot{Plots.PyPlotBackend}, Array{Float64, 1},))
    precompile(Plots.processLineArg, (Base.Dict{Symbol, Any}, Symbol,))
    precompile(Plots.aliasesAndAutopick, (Base.Dict{Symbol, Any}, Symbol, Base.Dict{Symbol, Any}, Array{Symbol, 1}, Int64,))
    precompile(Plots.plot!, (Array{Any, 1}, Plots.Plot{Plots.PyPlotBackend}, Array{Int64, 1},))
    precompile(Plots.pie, (Array{Any, 1}, Array{ASCIIString, 1},))
    precompile(Plots.aliasesAndAutopick, (Base.Dict{Symbol, Any}, Symbol, Base.Dict{Symbol, Any}, Array{Any, 1}, Int64,))
    precompile(Plots.merge_with_base_supported, (Array{Symbol, 1},))
    precompile(Plots.histogram2d, (Array{Any, 1}, Array{Float64, 1},))
    precompile(Plots.plot, (Array{Any, 1}, Base.StepRange{Int64, Int64}, Array{Float64, 2},))
    precompile(Plots.plot, (Array{Any, 1}, Base.LinSpace{Float64}, Array{Float64, 1},))
    precompile(Plots.plot, (Array{Any, 1}, Array{Float64, 1}, Array{Float64, 1},))
    precompile(Plots.font, ())
    precompile(Plots.plot, (Array{Any, 1}, Base.FloatRange{Float64}, Array{Float64, 1},))
    precompile(Plots.plot, (Array{Any, 1}, Base.FloatRange{Float64}, Base.FloatRange{Float64},))
    precompile(Plots.plot, (Array{Any, 1}, Array{Function, 1}, Array{Float64, 1},))
    precompile(Plots.scatter, (Array{Any, 1}, Base.LinSpace{Float64},))
    precompile(Plots.plot!, (Array{Any, 1}, Plots.Plot{Plots.PyPlotBackend}, Base.LinSpace{Float64},))
    precompile(Plots.plot!, (Array{Any, 1}, Base.LinSpace{Float64}, Array{Float64, 1},))
    precompile(Plots.get_zvalues, (Int64,))
    precompile(Plots.plot, (Array{Any, 1}, Array{Union{UTF8String, ASCIIString}, 1}, Array{Union{UTF8String, ASCIIString}, 1},))
    precompile(Plots.histogram, (Array{Any, 1}, Array{Float64, 1},))
    precompile(Plots.hline!, (Array{Any, 1}, Array{Float64, 2},))
    precompile(Plots.layout_args, (Base.Dict{Symbol, Any}, Int64,))
    precompile(Plots.heatmap, (Array{Any, 1}, Array{Union{UTF8String, ASCIIString}, 1},))
    precompile(Plots._replace_linewidth, (Base.Dict{Symbol, Any},))
    precompile(Plots.plot!, (Array{Any, 1}, Array{Float64, 1}, Array{Float64, 1},))
    precompile(Plots.plot!, (Array{Any, 1}, Plots.Plot{Plots.PyPlotBackend}, Array{Float64, 2},))
    precompile(Plots.py_markercolor, (Base.Dict{Symbol, Any},))
    precompile(Plots.unzip, (Array{Tuple{Float64, Float64}, 1},))
    precompile(Plots.link_axes!, (Array{Plots.AbstractLayout, 2}, Symbol,))
    precompile(Plots.plot!, (Array{Any, 1}, Plots.Plot{Plots.PyPlotBackend}, Array{Float64, 1},))
    precompile(Plots.contour, (Array{Any, 1}, Base.FloatRange{Float64},))
    precompile(Plots.scatter, (Array{Any, 1}, DataFrames.DataFrame,))
    precompile(Plots.scatter!, (Array{Any, 1}, Base.LinSpace{Float64},))
    precompile(Plots.scatter!, (Array{Any, 1}, Array{Float64, 1},))
    precompile(Plots.getxy, (Plots.Plot{Plots.PyPlotBackend}, Int64,))
    precompile(Plots.plot, (Array{Any, 1}, Array{Float64, 2},))
    precompile(Plots.get_xy, (Array{Plots.OHLC, 1}, Base.UnitRange{Int64},))
    precompile(Plots.convertToAnyVector, (Array{Function, 1}, Base.Dict{Symbol, Any},))
    precompile(Plots.py_add_annotations, (Plots.Subplot{Plots.PyPlotBackend}, Int64, Float64, Plots.PlotText,))
    precompile(Plots.plot!, (Array{Any, 1}, Array{Float64, 1},))
    precompile(Plots.get_color_palette, (Symbol, ColorTypes.RGB{Float64}, Int64,))
    precompile(Plots.py_add_annotations, (Plots.Subplot{Plots.PyPlotBackend}, Float64, Float64, Plots.PlotText,))
    precompile(Plots.py_colormap, (Plots.ColorGradient, Float64,))
    precompile(Plots.processMarkerArg, (Base.Dict{Symbol, Any}, Plots.Stroke,))
    precompile(Plots.call, (Type{Plots.ColorVector}, Array{Symbol, 1},))
    precompile(Plots.py_colormap, (Plots.ColorGradient, Void,))
    precompile(Plots.py_fillcolor, (Base.Dict{Symbol, Any},))
    precompile(Plots.processLineArg, (Base.Dict{Symbol, Any}, Float64,))
    precompile(Plots.plot!, (Array{Any, 1}, Array{Float64, 2},))
    precompile(Plots.processMarkerArg, (Base.Dict{Symbol, Any}, Symbol,))
    precompile(Plots.call, (Type{Plots.Plot},))
    precompile(Plots.call, (Type{Plots.ColorGradient}, Array{ColorTypes.RGBA{Float64}, 1},))
    precompile(Plots.plot!, (Array{Any, 1}, Array{Int64, 1},))
    precompile(Plots.getExtension, (UTF8String,))
    precompile(Plots.call, (Array{Any, 1}, Type{Plots.EmptyLayout},))
    precompile(Plots.update!, (Array{Any, 1}, Plots.Axis,))
    precompile(Plots.frame, (Plots.Animation, Plots.Plot{Plots.PyPlotBackend},))
    precompile(Plots.processMarkerArg, (Base.Dict{Symbol, Any}, Int64,))
    precompile(Plots.link_axes!, (Array{Plots.AbstractLayout, 1}, Symbol,))
    precompile(Plots.call, (Type{Plots.ColorGradient}, Array{ColorTypes.RGB{Float64}, 1},))
    precompile(Plots.fakedata, (Int64,))
    precompile(Plots.plot!, (Array{Any, 1}, Plots.Plot{Plots.PyPlotBackend},))
    precompile(Plots.py_compute_axis_minval, (Plots.Axis,))
    precompile(Plots.processLineArg, (Base.Dict{Symbol, Any}, Int64,))
    precompile(Plots.command_idx, (Array{Base.Dict{Symbol, Any}, 1}, Base.Dict{Symbol, Any},))
    precompile(Plots.getindex, (Plots.Axis, Symbol,))
    precompile(Plots.__init__, ())
    precompile(Plots.isvertical, (Base.Dict{Symbol, Any},))
    precompile(Plots.getExtension, (ASCIIString,))
    precompile(Plots.py_marker, (Symbol,))
    precompile(Plots.py_init_subplot, (Plots.Plot{Plots.PyPlotBackend}, Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.processMarkerArg, (Base.Dict{Symbol, Any}, ColorTypes.RGBA{Float64},))
    precompile(Plots.bucket_index, (Float64, Base.LinSpace{Float64},))
    precompile(Plots.default, (Array{Any, 1},))
    precompile(Plots.filter_data!, (Base.Dict{Symbol, Any}, Array{Int64, 1},))
    precompile(Plots.call, (Type{Plots.ColorGradient}, Array{Symbol, 1}, Base.LinSpace{Float64},))
    precompile(Plots.slice_arg, (Array{Symbol, 2}, Int64,))
    precompile(Plots.getindex, (Plots.Plot{Plots.UnicodePlotsBackend}, Symbol,))
    precompile(Plots.plot!, (Array{Any, 1},))
    precompile(Plots.push!, (Plots.Plot{Plots.PyPlotBackend}, Array{Float64, 1}, Array{Float64, 1},))
    precompile(Plots.processMarkerArg, (Base.Dict{Symbol, Any}, Float64,))
    precompile(Plots.expand_extrema!, (Plots.Axis, Base.FloatRange{Float64},))
    precompile(Plots.getindex, (Plots.Plot{Plots.PyPlotBackend}, Symbol,))
    precompile(Plots.handle_dfs, (DataFrames.DataFrame, Base.Dict{Symbol, Any}, ASCIIString, Symbol,))
    precompile(Plots.filter_data, (Base.UnitRange{Int64}, Array{Int64, 1},))
    precompile(Plots.call, (Type{Plots.ColorWrapper}, ColorTypes.RGBA{Float64},))
    precompile(Plots.processMarkerArg, (Base.Dict{Symbol, Any}, Array{Symbol, 2},))
    precompile(Plots.processLineArg, (Base.Dict{Symbol, Any}, Array{Symbol, 2},))
    precompile(Plots.color_or_nothing!, (Base.Dict{Symbol, Any}, Symbol,))
    precompile(Plots.processMarkerArg, (Base.Dict{Symbol, Any}, Plots.Shape,))
    precompile(Plots.py_fillcolormap, (Base.Dict{Symbol, Any},))
    precompile(Plots.transpose_z, (Base.Dict{Symbol, Any}, Array{Float64, 2}, Bool,))
    precompile(Plots.py_linecolor, (Base.Dict{Symbol, Any},))
    precompile(Plots.call, (Type{Plots.OHLC}, Float64, Float64, Float64, Float64,))
    precompile(Plots.setxy!, (Plots.Plot{Plots.PyPlotBackend}, Tuple{Array{Float64, 1}, Array{Float64, 1}}, Int64,))
    precompile(Plots.push!, (Plots.Segments, Float64, Float64, Float64, Float64,))
    precompile(Plots.handle_group, (DataFrames.DataFrame, Base.Dict{Symbol, Any},))
    precompile(Plots.lightness_from_background, (ColorTypes.RGB{Float64},))
    precompile(Plots.expand_extrema!, (Plots.Axis, Base.LinSpace{Float64},))
    precompile(Plots.py_bbox, (Array{Any, 1},))
    precompile(Plots.py_markerstrokecolor, (Base.Dict{Symbol, Any},))
    precompile(Plots.arrow, ())
    precompile(Plots.convert, (Type{Array{Float64, 1}}, Base.StepRange{Int64, Int64},))
    precompile(Plots.expand_extrema!, (Plots.Axis, Array{Float64, 1},))
    precompile(Plots.convertLegendValue, (Symbol,))
    precompile(Plots.slice_arg, (Array{Measures.Length{:mm, Float64}, 2}, Int64,))
    precompile(Plots.calc_num_subplots, (Plots.GridLayout,))
    precompile(Plots.processFillArg, (Base.Dict{Symbol, Any}, Int64,))
    precompile(Plots.slice_arg, (Array{Plots.ColorWrapper, 2}, Int64,))
    precompile(Plots.slice_arg, (Array{ASCIIString, 2}, Int64,))
    precompile(Plots.filter_data, (Array{Float64, 1}, Array{Int64, 1},))
    precompile(Plots.py_linecolormap, (Base.Dict{Symbol, Any},))
    precompile(Plots.discrete_value!, (Plots.Axis, ASCIIString,))
    precompile(Plots.allShapes, (ColorTypes.RGBA{Float64},))
    precompile(Plots.expand_extrema!, (Plots.Axis, Array{Int64, 1},))
    precompile(Plots.py_color_fix, (Tuple{Float64, Float64, Float64, Float64}, Base.LinSpace{Float64},))
    precompile(Plots.discrete_value!, (Plots.Axis, Symbol,))
    precompile(Plots.push!, (Plots.Segments, Float64, Int64, Int64, Float64,))
    precompile(Plots.expand_extrema!, (Plots.Axis, Plots.Surface{Array{Float64, 2}},))
    precompile(Plots.heatmap_edges, (Array{Float64, 1},))
    precompile(Plots.expand_extrema!, (Plots.Axis, Base.StepRange{Int64, Int64},))
    precompile(Plots.handleColors!, (Base.Dict{Symbol, Any}, Plots.Shape, Symbol,))
    precompile(Plots.py_color, (Plots.ColorWrapper, Float64,))
    precompile(Plots.call, (Type{Plots.GridLayout}, Int64, Int64,))
    precompile(Plots.handleColors!, (Base.Dict{Symbol, Any}, ColorTypes.RGBA{Float64}, Symbol,))
    precompile(Plots.handleColors!, (Base.Dict{Symbol, Any}, Bool, Symbol,))
    precompile(Plots.hvline_limits, (Plots.Axis,))
    precompile(Plots.current, ())
    precompile(Plots.handleColors!, (Base.Dict{Symbol, Any}, Float64, Symbol,))
    precompile(Plots.compute_gridsize, (Int64, Int64, Int64,))
    precompile(Plots.py_color, (ColorTypes.RGB{Float64}, Void,))
    precompile(Plots.interpolate_rgb, (ColorTypes.RGBA{Float64}, ColorTypes.RGBA{Float64}, Float64,))
    precompile(Plots.expand_extrema!, (Plots.Axis, Base.UnitRange{Int64},))
    precompile(Plots.allShapes, (Float64,))
    precompile(Plots.warn_on_deprecated_backend, (Symbol,))
    precompile(Plots.py_color_fix, (Tuple{Float64, Float64, Float64, Float64}, Array{Int64, 1},))
    precompile(Plots.setindex!, (Plots.GridLayout, Plots.EmptyLayout, Int64, Int64,))
    precompile(Plots.expand_extrema!, (Plots.Axis, Tuple{Int64, Int64},))
    precompile(Plots.allShapes, (Int64,))
    precompile(Plots.py_markercolormap, (Base.Dict{Symbol, Any},))
    precompile(Plots.interpolate_rgb, (ColorTypes.RGB{Float64}, ColorTypes.RGB{Float64}, Float64,))
    precompile(Plots.get_ticks, (Plots.Axis,))
    precompile(Plots.backend, ())
    precompile(Plots.get_xy, (Plots.OHLC{Float64}, Int64, Float64,))
    precompile(Plots.allShapes, (Plots.Stroke,))
    precompile(Plots.replaceAliases!, (Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any},))
    precompile(Plots._create_backend_figure, (Plots.Plot{Plots.PyPlotBackend},))
    precompile(Plots.png, (Plots.Plot{Plots.PyPlotBackend}, UTF8String,))
    precompile(Plots.processFillArg, (Base.Dict{Symbol, Any}, Symbol,))
    precompile(Plots.allShapes, (Plots.Shape,))
    precompile(Plots.handleColors!, (Base.Dict{Symbol, Any}, Plots.Stroke, Symbol,))
    precompile(Plots.py_color_fix, (Tuple{Float64, Float64, Float64, Float64}, Array{Float64, 1},))
    precompile(Plots.plot, (Array{Float64, 1},))
    precompile(Plots.rowsize, (Expr,))
    precompile(Plots.get_axis, (Plots.Subplot{Plots.PyPlotBackend}, Symbol,))
    precompile(Plots.png, (Plots.Plot{Plots.PyPlotBackend}, ASCIIString,))
    precompile(Plots.expand_extrema!, (Plots.Axis, Tuple{Float64, Float64},))
    precompile(Plots._markershape_supported, (Plots.PyPlotBackend, Plots.Shape,))
    precompile(Plots.processFillArg, (Base.Dict{Symbol, Any}, Bool,))
    precompile(Plots.supported_types, (Plots.PyPlotBackend,))
    precompile(Plots.get_axis, (Plots.Subplot{Plots.UnicodePlotsBackend}, Symbol,))
    precompile(Plots.setindex!, (Plots.GridLayout, Plots.GridLayout, Int64, Int64,))
    precompile(Plots.plot, ())
    precompile(Plots.py_color_fix, (Tuple{Float64, Float64, Float64, Float64}, Base.FloatRange{Float64},))
    precompile(Plots._markershape_supported, (Plots.PyPlotBackend, Symbol,))
    precompile(Plots.ok, (Float64, Float64, Int64,))
    precompile(Plots.allShapes, (Symbol,))
    precompile(Plots._initialize_backend, (Plots.PyPlotBackend,))
    precompile(Plots.plot, (Plots.Plot{Plots.PyPlotBackend}, Plots.Plot{Plots.PyPlotBackend},))
    precompile(Plots.bar, (Array{Float64, 1},))
    precompile(Plots.call, (Type{Plots.ColorGradient}, Array{ColorTypes.RGBA{Float64}, 1}, Base.LinSpace{Float64},))
    precompile(Plots.handleColors!, (Base.Dict{Symbol, Any}, Int64, Symbol,))
    precompile(Plots.nanappend!, (Array{Float64, 1}, Array{Float64, 1},))
    precompile(Plots.autopick, (Array{ColorTypes.RGBA, 1}, Int64,))
    precompile(Plots.compute_xyz, (Void, Array{Int64, 1}, Void,))
    precompile(Plots._add_markershape, (Base.Dict{Symbol, Any},))
    precompile(Plots._backend_instance, (Symbol,))
    precompile(Plots.py_color, (ColorTypes.RGBA{Float64}, Float64,))
    precompile(Plots.update_child_bboxes!, (Plots.GridLayout,))
    precompile(Plots._replace_markershape, (Symbol,))
    precompile(Plots.has_black_border_for_default, (Symbol,))
    precompile(Plots._filter_input_data!, (Base.Dict{Symbol, Any},))
    precompile(Plots.compute_xyz, (Array{Float64, 1}, Array{Float64, 1}, Base.UnitRange{Int64},))
    precompile(Plots.text, (ASCIIString, Int64, Symbol,))
    precompile(Plots.allShapes, (Array{Symbol, 2},))
    precompile(Plots.py_color_fix, (Tuple{Float64, Float64, Float64, Float64}, Base.UnitRange{Int64},))
    precompile(Plots.replaceAlias!, (Base.Dict{Symbol, Any}, Symbol, Base.Dict{Symbol, Any},))
    precompile(Plots.compute_xyz, (Array{ASCIIString, 1}, Array{Float64, 1}, Void,))
    precompile(Plots.layout_args, (Int64,))
    precompile(Plots.text, (ASCIIString, Symbol, Int64,))
    precompile(Plots.compute_xyz, (Base.FloatRange{Float64}, Base.FloatRange{Float64}, Plots.Surface{Array{Float64, 2}},))
    precompile(Plots.all3D, (Base.Dict{Symbol, Any},))
    precompile(Plots.cycle, (Array{Plots.Subplot, 1}, Int64,))
    precompile(Plots.compute_xyz, (Base.StepRange{Int64, Int64}, Array{Float64, 1}, Void,))
    precompile(Plots.plotarea!, (Plots.Subplot{Plots.PyPlotBackend}, Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}},))
    precompile(Plots.like_surface, (Symbol,))
    precompile(Plots.build_layout, (Base.Dict{Symbol, Any},))
    precompile(Plots.compute_xyz, (Array{Union{UTF8String, ASCIIString}, 1}, Array{Union{UTF8String, ASCIIString}, 1}, Plots.Surface{Array{Float64, 2}},))
    precompile(Plots.py_linestyle, (Symbol, Symbol,))
    precompile(Plots.plot!, (Array{Float64, 2},))
    precompile(Plots.plot!, (Plots.Plot{Plots.PyPlotBackend}, Array{Float64, 2},))
    precompile(Plots.call, (Type{Plots.ColorGradient}, Array{ColorTypes.RGB{Float64}, 1}, Base.LinSpace{Float64},))
    precompile(Plots.py_color, (ColorTypes.RGBA{Float64}, Void,))
    precompile(Plots.yaxis!, (ASCIIString, Symbol,))
    precompile(Plots.compute_xyz, (Base.LinSpace{Float64}, Array{Float64, 1}, Void,))
    precompile(Plots.isijulia, ())
    precompile(Plots.addExtension, (UTF8String, ASCIIString,))
    precompile(Plots.call, (Type{Plots.ColorGradient}, Array{ColorTypes.RGBA{Float64}, 1}, Array{Float64, 1},))
    precompile(Plots.expand_extrema!, (Plots.Subplot{Plots.PyPlotBackend}, Float64, Float64, Float64, Float64,))
    precompile(Plots.plotarea!, (Plots.GridLayout, Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}},))
    precompile(Plots.layout_args, (Base.Dict{Symbol, Any},))
    precompile(Plots.compute_xyz, (Base.FloatRange{Float64}, Array{Float64, 1}, Void,))
    precompile(Plots.addExtension, (ASCIIString, ASCIIString,))
    precompile(Plots.handleColors!, (Base.Dict{Symbol, Any}, Symbol, Symbol,))
    precompile(Plots._initialize_backend, (Plots.PlotlyBackend,))
    precompile(Plots.push!, (Plots.Plot{Plots.PyPlotBackend}, Int64, Float64, Float64,))
    precompile(Plots.bbox!, (Plots.Subplot{Plots.PyPlotBackend}, Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}},))
    precompile(Plots.vline!, (Array{Int64, 1},))
    precompile(Plots.supported_markers, (Plots.PyPlotBackend,))
    precompile(Plots.bbox!, (Plots.GridLayout, Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}},))
    precompile(Plots.stroke, (Int64,))
    precompile(Plots.compute_xyz, (Array{Float64, 1}, Array{Float64, 1}, Void,))
    precompile(Plots.right, (Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}},))
    precompile(Plots.extractGroupArgs, (Symbol, DataFrames.DataFrame, Symbol,))
    precompile(Plots.generate_colorgradient, (ColorTypes.RGB{Float64},))
    precompile(Plots.expand_extrema!, (Plots.Extrema, Bool,))
    precompile(Plots.py_colormap, (Plots.ColorWrapper, Void,))
    precompile(Plots.expand_extrema!, (Plots.Extrema, Float64,))
    precompile(Plots.contour, (Base.FloatRange{Float64},))
    precompile(Plots.bottom, (Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}},))
    precompile(Plots.text, (ASCIIString, Symbol,))
    precompile(Plots.create_grid, (Symbol,))
    precompile(Plots.expand_extrema!, (Plots.Axis, Bool,))
    precompile(Plots.handleColors!, (Base.Dict{Symbol, Any}, Array{Symbol, 2}, Symbol,))
    precompile(Plots.convertToAnyVector, (Void, Base.Dict{Symbol, Any},))
    precompile(Plots.py_dpi_scale, (Plots.Plot{Plots.PyPlotBackend}, Int64,))
    precompile(Plots.png, (ASCIIString,))
    precompile(Plots.supported_scales, (Plots.PyPlotBackend,))
    precompile(Plots.convertColor, (ColorTypes.RGBA{Float64}, Float64,))
    precompile(Plots.extendSeriesData, (Array{Float64, 1}, Float64,))
    precompile(Plots.compute_xyz, (Void, Array{Float64, 1}, Void,))
    precompile(Plots.py_color, (Symbol,))
    precompile(Plots.expand_extrema!, (Plots.Extrema, Int64,))
    precompile(Plots.supported_styles, (Plots.PyPlotBackend,))
    precompile(Plots._initialize_backend, (Plots.UnicodePlotsBackend,))
    precompile(Plots._initialize_backend, (Plots.GRBackend,))
    precompile(Plots.is3d, (Symbol,))
    precompile(Plots.supported_types, (Plots.UnicodePlotsBackend,))
    precompile(Plots.compute_xyz, (Array{Float64, 1}, Function, Void,))
    precompile(Plots.py_color, (Symbol, Void,))
    precompile(Plots.trueOrAllTrue, (Function, Array{Symbol, 2},))
    precompile(Plots.typemin, (Measures.Length{:mm, Float64},))
    precompile(Plots.expand_extrema!, (Plots.Axis, Float64,))
    precompile(Plots.get_subplot_index, (Plots.Plot{Plots.UnicodePlotsBackend}, Plots.Subplot{Plots.UnicodePlotsBackend},))
    precompile(Plots.leftpad, (Plots.GridLayout,))
    precompile(Plots._update_subplot_args, (Plots.Plot{Plots.UnicodePlotsBackend}, Plots.Subplot{Plots.UnicodePlotsBackend}, Base.Dict{Symbol, Any}, Int64,))
    precompile(Plots.centers, (Base.LinSpace{Float64},))
    precompile(Plots.expand_extrema!, (Plots.Axis, Int64,))
    precompile(Plots.text, (ASCIIString,))
    precompile(Plots.convertColor, (ColorTypes.RGB{Float64},))
    precompile(Plots.py_color, (Plots.ColorWrapper, Void,))
    precompile(Plots.py_color, (Plots.ColorWrapper,))
    precompile(Plots.trueOrAllTrue, (Function, Int64,))
    precompile(Plots.convertColor, (ColorTypes.RGBA{Float64},))
    precompile(Plots.extrema, (Plots.Axis,))
    precompile(Plots.top, (Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}},))
    precompile(Plots.convertColor, (Symbol,))
    precompile(Plots.size, (Plots.Surface{Array{Float64, 2}},))
    precompile(Plots.isdark, (ColorTypes.RGB{Float64},))
    precompile(Plots.rowsize, (Symbol,))
    precompile(Plots.series_list, (Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.convertToAnyVector, (Array{Float64, 1}, Base.Dict{Symbol, Any},))
    precompile(Plots.update!, (Plots.Axis,))
    precompile(Plots.push!, (Plots.Plot{Plots.PyPlotBackend}, Float64, Array{Float64, 1},))
    precompile(Plots.wraptuple, (Bool,))
    precompile(Plots.call, (Type{Plots.Shape}, Array{Tuple{Float64, Float64}, 1},))
    precompile(Plots.slice_arg, (Base.StepRange{Int64, Int64}, Int64,))
    precompile(Plots.sticks_fillfrom, (Void, Int64,))
    precompile(Plots.left, (Measures.BoundingBox{Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}, Tuple{Measures.Length{:mm, Float64}, Measures.Length{:mm, Float64}}},))
    precompile(Plots.gr, ())
    precompile(Plots.leftpad, (Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.supported_markers, ())
    precompile(Plots.colorscheme, (Symbol,))
    precompile(Plots.convertColor, (ColorTypes.RGB{Float64}, Void,))
    precompile(Plots.isscalar, (Int64,))
    precompile(Plots.wraptuple, (Int64,))
    precompile(Plots.call, (Type{Plots.Plot}, Plots.UnicodePlotsBackend, Int64, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Array{Plots.Series, 1}, Void, Array{Plots.Subplot, 1}, Base.Dict{Any, Plots.Subplot}, Plots.EmptyLayout, Array{Plots.Subplot, 1}, Bool,))
    precompile(Plots.supported_styles, ())
    precompile(Plots.frame, (Plots.Animation,))
    precompile(Plots.toppad, (Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.link_axes!, (Plots.Subplot{Plots.UnicodePlotsBackend}, Symbol,))
    precompile(Plots.convertLegendValue, (Bool,))
    precompile(Plots.convertColor, (ColorTypes.RGBA{Float64}, Void,))
    precompile(Plots.plotly, ())
    precompile(Plots.ispositive, (Measures.Length{:mm, Float64},))
    precompile(Plots.rightpad, (Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.call, (Type{Plots.GroupBy}, Array{ASCIIString, 1}, Array{Array{Int64, 1}, 1},))
    precompile(Plots.px2inch, (Int64,))
    precompile(Plots.slice_arg, (Tuple{Int64, Int64}, Int64,))
    precompile(Plots.call, (Type{Plots.UnicodePlotsBackend},))
    precompile(Plots.trueOrAllTrue, (Function, Symbol,))
    precompile(Plots.bottompad, (Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.annotate!, (Array{Tuple{Int64, Float64, Plots.PlotText}, 1},))
    precompile(Plots.get_subplot_index, (Plots.Plot{Plots.PyPlotBackend}, Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.call, (Type{Plots.Plot}, Plots.PyPlotBackend, Int64, Base.Dict{Symbol, Any}, Base.Dict{Symbol, Any}, Array{Plots.Series, 1}, Void, Array{Plots.Subplot, 1}, Base.Dict{Any, Plots.Subplot}, Plots.EmptyLayout, Array{Plots.Subplot, 1}, Bool,))
    precompile(Plots.title!, (ASCIIString,))
    precompile(Plots.slice_arg, (Bool, Int64,))
    precompile(Plots.wraptuple, (Float64,))
    precompile(Plots.bottompad, (Plots.GridLayout,))
    precompile(Plots.py_stepstyle, (Symbol,))
    precompile(Plots.link_axes!, (Plots.Subplot{Plots.PyPlotBackend}, Symbol,))
    precompile(Plots.call, (Type{Plots.GRBackend},))
    precompile(Plots.unicodeplots, ())
    precompile(Plots.rightpad, (Plots.GridLayout,))
    precompile(Plots.call, (Type{Plots.PlotlyBackend},))
    precompile(Plots.py_color, (ColorTypes.RGBA{Float64},))
    precompile(Plots.toppad, (Plots.GridLayout,))
    precompile(Plots.calc_edges, (Array{Float64, 1}, Int64,))
    precompile(Plots.colorscheme, (ColorTypes.RGBA{Float64},))
    precompile(Plots.slice_arg, (Int64, Int64,))
    precompile(Plots.pyplot, ())
    precompile(Plots._update_subplot_args, (Plots.Plot{Plots.PyPlotBackend}, Plots.Subplot{Plots.PyPlotBackend}, Base.Dict{Symbol, Any}, Int64,))
    precompile(Plots._series_added, (Plots.Plot{Plots.PyPlotBackend}, Plots.Series,))
    precompile(Plots.get_color_palette, (Array{ColorTypes.RGBA, 1}, ColorTypes.RGB{Float64}, Int64,))
    precompile(Plots._initialize_subplot, (Plots.Plot{Plots.UnicodePlotsBackend}, Plots.Subplot{Plots.UnicodePlotsBackend},))
    precompile(Plots.slice_arg, (Void, Int64,))
    precompile(Plots.cycle, (Int64, Int64,))
    precompile(Plots._initialize_subplot, (Plots.Plot{Plots.PyPlotBackend}, Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.call, (Type{Plots.PyPlotBackend},))
    precompile(Plots.update_child_bboxes!, (Plots.Subplot{Plots.PyPlotBackend}, Array{Measures.Length{:mm, Float64}, 1},))
    precompile(Plots.filter_data, (Void, Array{Int64, 1},))
    precompile(Plots.slice_arg, (Symbol, Int64,))
    precompile(Plots.slice_arg, (ASCIIString, Int64,))
    precompile(Plots.layout_args, (Plots.GridLayout,))
    precompile(Plots.wraptuple, (Tuple{},))
    precompile(Plots.calc_num_subplots, (Plots.EmptyLayout,))
    precompile(Plots.wraptuple, (Tuple{Symbol, Float64, Plots.Stroke},))
    precompile(Plots.wraptuple, (Tuple{ASCIIString, Tuple{Int64, Int64}, Base.StepRange{Int64, Int64}, Symbol},))
    precompile(Plots.wraptuple, (Tuple{Int64, Symbol, Float64, Array{Symbol, 2}},))
    precompile(Plots.wraptuple, (Tuple{Int64, Array{Symbol, 2}},))
    precompile(Plots.wraptuple, (Tuple{ASCIIString, Symbol},))
    precompile(Plots._replace_markershape, (Array{Symbol, 2},))
    precompile(Plots.wraptuple, (Tuple{Symbol, Int64},))
    precompile(Plots.wraptuple, (Tuple{Array{Symbol, 2}, Int64},))
    precompile(Plots.wraptuple, (Tuple{Int64, Symbol, Symbol},))
    precompile(Plots.wraptuple, (Tuple{Int64, Float64, Symbol, Plots.Stroke},))
    precompile(Plots.wraptuple, (Tuple{Float64, Array{Symbol, 2}, Int64},))
    precompile(Plots.py_color, (ColorTypes.RGB{Float64},))
    precompile(Plots.wraptuple, (Tuple{Int64, Float64, Symbol},))
    precompile(Plots.tovec, (Array{Float64, 1},))
    precompile(Plots.get_subplot, (Plots.Plot{Plots.PyPlotBackend}, Plots.Subplot{Plots.PyPlotBackend},))
    precompile(Plots.eltype, (Plots.Surface{Array{Float64, 2}},))
    precompile(Plots.nobigs, (Array{Float64, 1},))
    precompile(Plots.get_subplot, (Plots.Plot{Plots.UnicodePlotsBackend}, Plots.Subplot{Plots.UnicodePlotsBackend},))
    precompile(Plots.annotations, (Array{Any, 1},))
    precompile(Plots.wraptuple, (Tuple{Int64, Symbol},))
    precompile(Plots.colorscheme, (Plots.ColorWrapper,))
    precompile(Plots.colorscheme, (Plots.ColorGradient,))
    precompile(Plots.text, (Plots.PlotText,))
    precompile(Plots._replace_markershape, (Plots.Shape,))
    precompile(Plots.wraptuple, (Tuple{Array{Symbol, 2}, Int64, Float64, Plots.Stroke},))
    precompile(Plots.wraptuple, (Tuple{Plots.Shape, Int64, ColorTypes.RGBA{Float64}},))
end
