name: formatting

on:
  push:
    branches: ['release-', 'master', 'v2']
    tags:
      - '*'
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  runic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v2
      - uses: fredrikekre/runic-action@v1
