name: tagbot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  tagbot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - name: Clone latest General registry
        run: git clone --depth 1 https://github.com/JuliaRegistries/General.git /tmp/General
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.TAGBOT_KEY }}
          branch: master
          subdir: Plots
          registry: /tmp/General
